import React from 'react';
import Paper from '@mui/material/Paper';
import Card from '@mui/material/Card';
import CardMedia from '@mui/material/CardMedia';
import Grid from '@mui/material/Grid';
import { styled } from '@mui/material/styles';

const MediaGrid = styled(Grid)(({ theme }) => ({
  [theme.breakpoints.up('xs')]: {
    maxWidth: "100%"
  },
  [theme.breakpoints.up('sm')]: {
    minWidth: "20rem",
    maxWidth: "70%"
  },
  [theme.breakpoints.up('md')]: {
    minWidth: "25rem",
  },
}));

const WidthGrid = styled(Grid)(({ theme }) => ({
  [theme.breakpoints.up('xs')]: {
    minWidth: "17rem",
  },
}));


const BreakGrid = styled(Grid)(({ theme }) => ({
  [theme.breakpoints.up('xs')]: {
    margin: "0 5vh 0 5vh"
  },
  [theme.breakpoints.up('sm')]: {
    margin: "0 5vh 0 5vh"
  },
  [theme.breakpoints.up('md')]: {
    minWidth: "40rem"
  },

}));


export default function AncientScrolls() {

  return (
    <React.Fragment>

      <Paper
        elevation={3}
        sx={{
          width: "80vw",
          minHeight: "90vh",
          padding: "0 0 5vh 0",
          display: "flex",
          justifyContent: "center",
          backgroundColor: "white",
          backgroundImage: "url('./images/stone_limited.png')",
          backgroundSize: "960px"
        }}
      >
        <BreakGrid
          container
          nowrap
          direction="row"
          justifyContent="space-evenly"
          alignItems="top"
          style={{marginTop: "5rem"}}
          spacing={1}
        >
          <WidthGrid item
            md={4}
            xs={12}
          >

            <Card
              class="rpgui-container framed-custom-2"
            >
              The Ancient Scrolls are 2048 weird NFT stories generated by an AI who shall henceforth be referred to as Jeff. The illustrations in each story are done by Jeff's partner, an AI named Phrank. As the scroll unrolls the story is reavealed, each story is inspired by one Grimms fairy tales but is a completely new work.
            </Card>
            <Card
              class="rpgui-container framed-custom-2"
              style={{
                marginTop: "3rem",
                marginBottom: "3rem"
              }}
            >
              The AI has 
              Three illustrations in each story are done in the 
            </Card>
          </WidthGrid>
          <MediaGrid item
            md={4}
            xs={12}
          >

            <Card
              class="rpgui-container framed-custom-3"
            >
              <CardMedia
                component="img"
                image="/images/example_image_1.png"
                sx={{
                  transform: "scale(0.8)",
                  border: 7,
                  borderColor: "black"
                }}
                alt="Scroll NFT Example 1"
              />
            </Card>
          </MediaGrid>
        </BreakGrid>

      </Paper>
    </React.Fragment>
  );
}
